services:
  backend:
    build: ./backend
    container_name: node-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - fullstack-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:3000"
    networks:
      - fullstack-net
    depends_on:
      - backend
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge
